# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Talent Cash' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	  pod 'SwiftyJSON'
  	pod 'SDWebImage'
	pod 'SDWebImageFLPlugin'
    	pod 'Cosmos', '~> 18.0'
    	pod 'Reusable',  '~> 4.1'
    	#pod 'SwiftMessages'
    	pod 'OTPFieldView'
    	pod 'FBSDKCoreKit'
    	pod 'FBSDKLoginKit'
    	pod 'Firebase/Core'
    	pod 'Firebase/Auth'
    	pod 'GoogleSignIn', '~> 5.0.2'
    	pod "KYShutterButton"
    	#pod "NextLevel"
    	pod 'MarqueeLabel'
    	pod 'YPImagePicker'
    	pod 'DSGradientProgressView'
    	pod 'GSPlayer'
    	pod 'NVActivityIndicatorView'
    	#pod "Player"
    	pod 'GooglePlaces'
    	pod 'DPOTPView'
    	pod 'IQKeyboardManagerSwift'
    	pod 'CountryPickerView'
    	pod 'FirebaseDatabase'
    	pod 'FirebaseStorage'
    	pod 'FirebaseMessaging'
    	pod 'FirebaseCore'
    	pod 'KDCircularProgress'
    	pod 'GoogleMaps'
      pod 'PryntTrimmerView'
      pod "MediaWatermark"
      pod 'DPVideoMerger-Swift'
	pod "GTProgressBar"
    	pod 'ActiveLabel'
      	pod 'AcceptCardSDK'
end
